In [34]:
import pandas as pd
import numpy as np

In [35]:
df = pd.read_csv("week5_finance_cleaned.csv")
df.head()

,date,open,high,low,close,volume,name,year,month,daily_return,trend,price_change
0,2013-02-08,15.07,15.12,14.63,14.75,8407500.0,AAL,2013,Feb,-0.019661,Loss,-0.32
1,2013-02-11,14.89,15.01,14.26,14.46,8882000.0,AAL,2013,Feb,-0.013140,Loss,-0.43
2,2013-02-12,14.45,14.51,14.10,14.27,8126000.0,AAL,2013,Feb,0.027330,Loss,-0.18
3,2013-02-13,14.30,14.94,14.25,14.66,10259500.0,AAL,2013,Feb,-0.045703,Profit,0.36
4,2013-02-14,14.94,14.96,13.16,13.99,31879900.0,AAL,2013,Feb,0.036455,Loss,-0.95

In [36]:
df.columns

Index(['date', 'open', 'high', 'low', 'close', 'volume', 'name', 'year',
       'month', 'daily_return', 'trend', 'price_change'],
      dtype='object')

In [37]:
df['name'].unique()

array(['AAL', 'AAPL', 'AAP', 'ABBV', 'ABC', 'ABT', 'ACN', 'ADBE', 'ADI',
       'ADM', 'ADP', 'ADSK', 'ADS', 'AEE', 'AEP', 'AES', 'AET', 'AFL',
       'AGN', 'AIG', 'AIV', 'AIZ', 'AJG', 'AKAM', 'ALB', 'ALGN', 'ALK',
       'ALLE', 'ALL', 'ALXN', 'AMAT', 'AMD', 'AME', 'AMGN', 'AMG', 'AMP',
       'AMT', 'AMZN', 'ANDV', 'ANSS', 'ANTM', 'AON', 'AOS', 'APA', 'APC',
       'APD', 'APH', 'APTV', 'ARE', 'ARNC', 'ATVI', 'AVB', 'AVGO', 'AVY',
       'AWK', 'AXP', 'AYI', 'AZO', 'A', 'BAC', 'BAX', 'BA', 'BBT', 'BBY',
       'BDX', 'BEN', 'BF.B', 'BHF', 'BHGE', 'BIIB', 'BK', 'BLK', 'BLL',
       'BMY', 'BRK.B', 'BSX', 'BWA', 'BXP', 'CAG', 'CAH', 'CAT', 'CA',
       'CBG', 'CBOE', 'CBS', 'CB', 'CCI', 'CCL', 'CDNS', 'CELG', 'CERN',
       'CFG', 'CF', 'CHD', 'CHK', 'CHRW', 'CHTR', 'CINF', 'CI', 'CLX',
       'CL', 'CMA', 'CMCSA', 'CME', 'CMG', 'CMI', 'CMS', 'CNC', 'CNP',
       'COF', 'COG', 'COL', 'COO', 'COP', 'COST', 'COTY', 'CPB', 'CRM',
       'CSCO', 'CSRA', 'CSX', 'CTAS', 'CTL', 'CTSH', 'CTXS', 'CVS', 'CVX',
       'CXO', 'C', 'DAL', 'DE', 'DFS', 'DGX', 'DG', 'DHI', 'DHR', 'DISCA',
       'DISCK', 'DISH', 'DIS', 'DLR', 'DLTR', 'DOV', 'DPS', 'DRE', 'DRI',
       'DTE', 'DUK', 'DVA', 'DVN', 'DWDP', 'DXC', 'D', 'EA', 'EBAY',
       'ECL', 'ED', 'EFX', 'EIX', 'EL', 'EMN', 'EMR', 'EOG', 'EQIX',
       'EQR', 'EQT', 'ESRX', 'ESS', 'ES', 'ETFC', 'ETN', 'ETR', 'EVHC',
       'EW', 'EXC', 'EXPD', 'EXPE', 'EXR', 'FAST', 'FBHS', 'FB', 'FCX',
       'FDX', 'FE', 'FFIV', 'FISV', 'FIS', 'FITB', 'FLIR', 'FLR', 'FLS',
       'FL', 'FMC', 'FOXA', 'FOX', 'FRT', 'FTI', 'FTV', 'F', 'GD', 'GE',
       'GGP', 'GILD', 'GIS', 'GLW', 'GM', 'GOOGL', 'GOOG', 'GPC', 'GPN',
       'GPS', 'GRMN', 'GS', 'GT', 'GWW', 'HAL', 'HAS', 'HBAN', 'HBI',
       'HCA', 'HCN', 'HCP', 'HD', 'HES', 'HIG', 'HII', 'HLT', 'HOG',
       'HOLX', 'HON', 'HPE', 'HPQ', 'HP', 'HRB', 'HRL', 'HRS', 'HSIC',
       'HST', 'HSY', 'HUM', 'IBM', 'ICE', 'IDXX', 'IFF', 'ILMN', 'INCY',
       'INFO', 'INTC', 'INTU', 'IPG', 'IP', 'IQV', 'IRM', 'IR', 'ISRG',
       'ITW', 'IT', 'IVZ', 'JBHT', 'JCI', 'JEC', 'JNJ', 'JNPR', 'JPM',
       'JWN', 'KEY', 'KHC', 'KIM', 'KLAC', 'KMB', 'KMI', 'KMX', 'KORS',
       'KO', 'KR', 'KSS', 'KSU', 'K', 'LB', 'LEG', 'LEN', 'LH', 'LKQ',
       'LLL', 'LLY', 'LMT', 'LNC', 'LNT', 'LOW', 'LRCX', 'LUK', 'LUV',
       'LYB', 'L', 'MAA', 'MAC', 'MAR', 'MAS', 'MAT', 'MA', 'MCD', 'MCHP',
       'MCK', 'MCO', 'MDLZ', 'MDT', 'MET', 'MGM', 'MHK', 'MKC', 'MLM',
       'MMC', 'MMM', 'MNST', 'MON', 'MOS', 'MO', 'MPC', 'MRK', 'MRO',
       'MSFT', 'MSI', 'MS', 'MTB', 'MTD', 'MU', 'MYL', 'M', 'NAVI', 'NBL',
       'NCLH', 'NDAQ', 'NEE', 'NEM', 'NFLX', 'NFX', 'NI', 'NKE', 'NLSN',
       'NOC', 'NOV', 'NRG', 'NSC', 'NTAP', 'NTRS', 'NUE', 'NVDA', 'NWL',
       'NWSA', 'NWS', 'OKE', 'OMC', 'ORCL', 'ORLY', 'OXY', 'O', 'PAYX',
       'PBCT', 'PCAR', 'PCG', 'PCLN', 'PDCO', 'PEG', 'PEP', 'PFE', 'PFG',
       'PGR', 'PG', 'PHM', 'PH', 'PKG', 'PKI', 'PLD', 'PM', 'PNC', 'PNR',
       'PNW', 'PPG', 'PPL', 'PRGO', 'PRU', 'PSA', 'PSX', 'PVH', 'PWR',
       'PXD', 'PX', 'PYPL', 'QCOM', 'QRVO', 'RCL', 'REGN', 'REG', 'RE',
       'RF', 'RHI', 'RHT', 'RJF', 'RL', 'RMD', 'ROK', 'ROP', 'ROST',
       'RRC', 'RSG', 'RTN', 'SBAC', 'SBUX', 'SCG', 'SCHW', 'SEE', 'SHW',
       'SIG', 'SJM', 'SLB', 'SLG', 'SNA', 'SNI', 'SNPS', 'SO', 'SPGI',
       'SPG', 'SRCL', 'SRE', 'STI', 'STT', 'STX', 'STZ', 'SWKS', 'SWK',
       'SYF', 'SYK', 'SYMC', 'SYY', 'TAP', 'TDG', 'TEL', 'TGT', 'TIF',
       'TJX', 'TMK', 'TMO', 'TPR', 'TRIP', 'TROW', 'TRV', 'TSCO', 'TSN',
       'TSS', 'TWX', 'TXN', 'TXT', 'T', 'UAA', 'UAL', 'UA', 'UDR', 'UHS',
       'ULTA', 'UNH', 'UNM', 'UNP', 'UPS', 'URI', 'USB', 'UTX', 'VAR',
       'VFC', 'VIAB', 'VLO', 'VMC', 'VNO', 'VRSK', 'VRSN', 'VRTX', 'VTR',
       'VZ', 'V', 'WAT', 'WBA', 'WDC', 'WEC', 'WFC', 'WHR', 'WLTW', 'WMB',
       'WMT', 'WM', 'WRK', 'WU', 'WYNN', 'WYN', 'WY', 'XEC', 'XEL',
       'XLNX', 'XL', 'XOM', 'XRAY', 'XRX', 'XYL', 'YUM', 'ZBH', 'ZION',
       'ZTS'], dtype=object)

In [38]:
returns_wide = df.pivot(
    index='date',
    columns='name',
    values='daily_return'
)

returns_wide.head()

name,A,AAL,AAP,AAPL,ABBV,ABC,ABT,ACN,ADBE,ADI,...,XL,XLNX,XOM,XRAY,XRX,XYL,YUM,ZBH,ZION,ZTS
date,,,,,,,,,,,,,,,,,,,,,
NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2013-02-08,-0.010648,-0.019661,-0.006464,0.010422,-0.011034,-0.002772,-0.004359,-0.003274,-0.012270,0.008315,...,0.002479,-0.001333,-0.003724,-0.000700,0.003769,0.013658,-0.011485,-0.002637,0.002900,0.006354
2013-02-11,0.000448,-0.013140,0.002679,-0.025067,-0.011994,0.004277,0.001168,0.004106,0.006470,0.004123,...,0.003532,0.003203,0.002039,0.000700,-0.003755,0.017844,0.003098,-0.002776,0.011565,0.014432
2013-02-12,0.002913,0.027330,0.004707,-0.001903,-0.004235,-0.006814,0.004665,0.002590,-0.002057,-0.000216,...,0.000352,0.005854,0.002374,0.004899,0.005025,0.011091,-0.005251,0.007423,0.010208,-0.005631
2013-02-13,-0.003799,-0.045703,-0.001646,-0.000899,0.036859,0.002787,0.006965,-0.005846,-0.005153,0.006053,...,-0.007037,0.016931,-0.001692,-0.003946,0.003750,0.007431,-0.008073,0.004474,-0.004446,-0.008346

In [39]:
returns_wide = returns_wide.dropna()

In [40]:
num_stocks = returns_wide.shape[1]
weights = np.array([1/num_stocks] * num_stocks)
weights

array([0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802])

In [41]:
returns_wide['Portfolio_Return'] = returns_wide.dot(weights)
returns_wide.head()

name,A,AAL,AAP,AAPL,ABBV,ABC,ABT,ACN,ADBE,ADI,...,XLNX,XOM,XRAY,XRX,XYL,YUM,ZBH,ZION,ZTS,Portfolio_Return
date,,,,,,,,,,,,,,,,,,,,,
2017-12-05,0.000911,0.002830,-0.036085,-0.003714,-0.010586,0.001164,-0.002373,0.004063,0.035693,0.006837,...,-0.000438,-0.007359,-0.001677,0.006793,0.002064,0.001685,0.002511,-0.018868,0.001694,-0.002062
2017-12-06,0.012445,0.025600,0.001128,0.001834,-0.001695,-0.000698,0.000549,0.002226,0.006282,0.008196,...,0.008919,0.003281,-0.007786,-0.001687,0.005884,-0.002283,-0.008637,0.011018,0.009441,0.004293
2017-12-07,0.010043,0.002752,0.027661,0.000295,0.018145,0.008961,-0.000914,0.012988,-0.005956,-0.006852,...,-0.006667,0.001333,-0.001385,0.000000,-0.002779,0.003251,-0.012197,0.009114,0.003350,0.006472
2017-12-08,-0.005640,0.005488,0.005383,0.019484,0.005419,0.000807,0.005490,0.001063,0.004263,0.003274,...,-0.002334,0.004476,0.001849,0.000000,-0.013345,-0.010442,0.001147,-0.019438,-0.001530,0.001217
2017-12-11,0.000896,-0.016179,0.021616,-0.005618,-0.001762,0.012101,0.013833,0.009357,-0.010154,-0.003730,...,-0.010237,-0.003252,-0.000461,0.005069,0.003864,-0.005579,0.000264,0.010412,0.006409,-0.000299

In [42]:
portfolio_df = returns_wide.reset_index()
portfolio_df.head()

name,date,A,AAL,AAP,AAPL,ABBV,ABC,ABT,ACN,ADBE,...,XLNX,XOM,XRAY,XRX,XYL,YUM,ZBH,ZION,ZTS,Portfolio_Return
0,2017-12-05,0.000911,0.002830,-0.036085,-0.003714,-0.010586,0.001164,-0.002373,0.004063,0.035693,...,-0.000438,-0.007359,-0.001677,0.006793,0.002064,0.001685,0.002511,-0.018868,0.001694,-0.002062
1,2017-12-06,0.012445,0.025600,0.001128,0.001834,-0.001695,-0.000698,0.000549,0.002226,0.006282,...,0.008919,0.003281,-0.007786,-0.001687,0.005884,-0.002283,-0.008637,0.011018,0.009441,0.004293
2,2017-12-07,0.010043,0.002752,0.027661,0.000295,0.018145,0.008961,-0.000914,0.012988,-0.005956,...,-0.006667,0.001333,-0.001385,0.000000,-0.002779,0.003251,-0.012197,0.009114,0.003350,0.006472
3,2017-12-08,-0.005640,0.005488,0.005383,0.019484,0.005419,0.000807,0.005490,0.001063,0.004263,...,-0.002334,0.004476,0.001849,0.000000,-0.013345,-0.010442,0.001147,-0.019438,-0.001530,0.001217
4,2017-12-11,0.000896,-0.016179,0.021616,-0.005618,-0.001762,0.012101,0.013833,0.009357,-0.010154,...,-0.010237,-0.003252,-0.000461,0.005069,0.003864,-0.005579,0.000264,0.010412,0.006409,-0.000299

In [43]:
portfolio_df.to_csv("alpha_pulse_portfolio.csv", index=False)

In [44]:
df.columns

Index(['date', 'open', 'high', 'low', 'close', 'volume', 'name', 'year',
       'month', 'daily_return', 'trend', 'price_change'],
      dtype='object')

In [45]:
df['daily_return'].isna().sum()

np.int64(0)

In [46]:
df = df.dropna(subset=['daily_return'])

In [47]:
returns_wide = df.pivot_table(
    index='date',
    columns='name',
    values='daily_return'
)

In [48]:
returns_wide.head()

name,A,AAL,AAP,AAPL,ABBV,ABC,ABT,ACN,ADBE,ADI,...,XL,XLNX,XOM,XRAY,XRX,XYL,YUM,ZBH,ZION,ZTS
date,,,,,,,,,,,,,,,,,,,,,
2013-02-08,-0.010648,-0.019661,-0.006464,0.010422,-0.011034,-0.002772,-0.004359,-0.003274,-0.012270,0.008315,...,0.002479,-0.001333,-0.003724,-0.000700,0.003769,0.013658,-0.011485,-0.002637,0.002900,0.006354
2013-02-11,0.000448,-0.013140,0.002679,-0.025067,-0.011994,0.004277,0.001168,0.004106,0.006470,0.004123,...,0.003532,0.003203,0.002039,0.000700,-0.003755,0.017844,0.003098,-0.002776,0.011565,0.014432
2013-02-12,0.002913,0.027330,0.004707,-0.001903,-0.004235,-0.006814,0.004665,0.002590,-0.002057,-0.000216,...,0.000352,0.005854,0.002374,0.004899,0.005025,0.011091,-0.005251,0.007423,0.010208,-0.005631
2013-02-13,-0.003799,-0.045703,-0.001646,-0.000899,0.036859,0.002787,0.006965,-0.005846,-0.005153,0.006053,...,-0.007037,0.016931,-0.001692,-0.003946,0.003750,0.007431,-0.008073,0.004474,-0.004446,-0.008346
2013-02-14,-0.052266,0.036455,0.002029,-0.013780,0.027618,-0.003635,0.010951,0.014085,0.000648,-0.007843,...,0.015946,-0.008325,-0.001808,-0.002564,-0.007472,-0.006674,0.001565,-0.005764,-0.011774,0.021341

In [49]:
returns_wide = returns_wide.dropna()

In [50]:
returns_wide.shape

(44, 505)

In [51]:
num_stocks = returns_wide.shape[1]
weights = np.repeat(1/num_stocks, num_stocks)
weights

array([0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802, 0.0019802,
       0.0019802])

In [52]:
returns_wide['Portfolio_Return'] = returns_wide.dot(weights)

In [53]:
returns_wide.head()

name,A,AAL,AAP,AAPL,ABBV,ABC,ABT,ACN,ADBE,ADI,...,XLNX,XOM,XRAY,XRX,XYL,YUM,ZBH,ZION,ZTS,Portfolio_Return
date,,,,,,,,,,,,,,,,,,,,,
2017-12-05,0.000911,0.002830,-0.036085,-0.003714,-0.010586,0.001164,-0.002373,0.004063,0.035693,0.006837,...,-0.000438,-0.007359,-0.001677,0.006793,0.002064,0.001685,0.002511,-0.018868,0.001694,-0.002062
2017-12-06,0.012445,0.025600,0.001128,0.001834,-0.001695,-0.000698,0.000549,0.002226,0.006282,0.008196,...,0.008919,0.003281,-0.007786,-0.001687,0.005884,-0.002283,-0.008637,0.011018,0.009441,0.004293
2017-12-07,0.010043,0.002752,0.027661,0.000295,0.018145,0.008961,-0.000914,0.012988,-0.005956,-0.006852,...,-0.006667,0.001333,-0.001385,0.000000,-0.002779,0.003251,-0.012197,0.009114,0.003350,0.006472
2017-12-08,-0.005640,0.005488,0.005383,0.019484,0.005419,0.000807,0.005490,0.001063,0.004263,0.003274,...,-0.002334,0.004476,0.001849,0.000000,-0.013345,-0.010442,0.001147,-0.019438,-0.001530,0.001217
2017-12-11,0.000896,-0.016179,0.021616,-0.005618,-0.001762,0.012101,0.013833,0.009357,-0.010154,-0.003730,...,-0.010237,-0.003252,-0.000461,0.005069,0.003864,-0.005579,0.000264,0.010412,0.006409,-0.000299

In [54]:
portfolio_df = returns_wide.reset_index()
portfolio_df.head()

name,date,A,AAL,AAP,AAPL,ABBV,ABC,ABT,ACN,ADBE,...,XLNX,XOM,XRAY,XRX,XYL,YUM,ZBH,ZION,ZTS,Portfolio_Return
0,2017-12-05,0.000911,0.002830,-0.036085,-0.003714,-0.010586,0.001164,-0.002373,0.004063,0.035693,...,-0.000438,-0.007359,-0.001677,0.006793,0.002064,0.001685,0.002511,-0.018868,0.001694,-0.002062
1,2017-12-06,0.012445,0.025600,0.001128,0.001834,-0.001695,-0.000698,0.000549,0.002226,0.006282,...,0.008919,0.003281,-0.007786,-0.001687,0.005884,-0.002283,-0.008637,0.011018,0.009441,0.004293
2,2017-12-07,0.010043,0.002752,0.027661,0.000295,0.018145,0.008961,-0.000914,0.012988,-0.005956,...,-0.006667,0.001333,-0.001385,0.000000,-0.002779,0.003251,-0.012197,0.009114,0.003350,0.006472
3,2017-12-08,-0.005640,0.005488,0.005383,0.019484,0.005419,0.000807,0.005490,0.001063,0.004263,...,-0.002334,0.004476,0.001849,0.000000,-0.013345,-0.010442,0.001147,-0.019438,-0.001530,0.001217
4,2017-12-11,0.000896,-0.016179,0.021616,-0.005618,-0.001762,0.012101,0.013833,0.009357,-0.010154,...,-0.010237,-0.003252,-0.000461,0.005069,0.003864,-0.005579,0.000264,0.010412,0.006409,-0.000299

In [55]:
portfolio_df.to_csv("alpha_pulse_portfolio1.csv", index=False)

In [56]:
portfolio_df.columns

Index(['date', 'A', 'AAL', 'AAP', 'AAPL', 'ABBV', 'ABC', 'ABT', 'ACN', 'ADBE',
       ...
       'XLNX', 'XOM', 'XRAY', 'XRX', 'XYL', 'YUM', 'ZBH', 'ZION', 'ZTS',
       'Portfolio_Return'],
      dtype='object', name='name', length=507)

In [57]:
df = pd.read_csv("alpha_pulse_portfolio.csv")
df.head()

,date,A,AAL,AAP,AAPL,ABBV,ABC,ABT,ACN,ADBE,...,XLNX,XOM,XRAY,XRX,XYL,YUM,ZBH,ZION,ZTS,Portfolio_Return
0,2017-12-05,0.000911,0.002830,-0.036085,-0.003714,-0.010586,0.001164,-0.002373,0.004063,0.035693,...,-0.000438,-0.007359,-0.001677,0.006793,0.002064,0.001685,0.002511,-0.018868,0.001694,-0.002062
1,2017-12-06,0.012445,0.025600,0.001128,0.001834,-0.001695,-0.000698,0.000549,0.002226,0.006282,...,0.008919,0.003281,-0.007786,-0.001687,0.005884,-0.002283,-0.008637,0.011018,0.009441,0.004293
2,2017-12-07,0.010043,0.002752,0.027661,0.000295,0.018145,0.008961,-0.000914,0.012988,-0.005956,...,-0.006667,0.001333,-0.001385,0.000000,-0.002779,0.003251,-0.012197,0.009114,0.003350,0.006472
3,2017-12-08,-0.005640,0.005488,0.005383,0.019484,0.005419,0.000807,0.005490,0.001063,0.004263,...,-0.002334,0.004476,0.001849,0.000000,-0.013345,-0.010442,0.001147,-0.019438,-0.001530,0.001217
4,2017-12-11,0.000896,-0.016179,0.021616,-0.005618,-0.001762,0.012101,0.013833,0.009357,-0.010154,...,-0.010237,-0.003252,-0.000461,0.005069,0.003864,-0.005579,0.000264,0.010412,0.006409,-0.000299

In [58]:
portfolio_returns = df['Portfolio_Return']

In [59]:
portfolio_returns.describe()

count    44.000000
mean      0.000289
std       0.008359
min      -0.036907
25%      -0.002488
50%       0.000685
75%       0.005744
max       0.013354
Name: Portfolio_Return, dtype: float64

In [60]:
var_95 = np.percentile(portfolio_returns, 5)
var_99 = np.percentile(portfolio_returns, 1)
print("95% Historical VaR:", var_95)
print("99% Historical VaR:", var_99)

95% Historical VaR: -0.01058507979837389
99% Historical VaR: -0.029699709708200576

In [61]:
df['Rolling_Vol_30'] = portfolio_returns.rolling(30).std()

In [62]:
df[['date', 'Rolling_Vol_30']].dropna().head()

          date  Rolling_Vol_30
29  2018-01-18        0.004531
30  2018-01-19        0.004551
31  2018-01-22        0.004540
32  2018-01-23        0.004485
33  2018-01-24        0.004510

In [63]:
returns_only = df.drop(columns=['date', 'Portfolio_Return', 'Rolling_Vol_30'])

In [64]:
corr_matrix = returns_only.corr()
corr_matrix

,A,AAL,AAP,AAPL,ABBV,ABC,ABT,ACN,ADBE,ADI,...,XL,XLNX,XOM,XRAY,XRX,XYL,YUM,ZBH,ZION,ZTS
A,1.000000,-0.907589,0.984500,0.986867,0.966124,0.991477,-0.924672,0.997763,0.995119,0.991504,...,-0.986321,0.983492,0.986527,0.975105,0.785403,0.798226,0.703918,0.992849,0.980650,0.997323
AAL,-0.907589,1.000000,-0.881803,-0.866889,-0.878837,-0.899468,0.871522,-0.905642,-0.893861,-0.880124,...,0.916096,-0.861252,-0.871132,-0.894916,-0.588178,-0.699390,-0.482250,-0.913818,-0.855028,-0.919405
AAP,0.984500,-0.881803,1.000000,0.982132,0.962255,0.980183,-0.894052,0.985529,0.981711,0.981333,...,-0.974145,0.972569,0.981008,0.971609,0.785949,0.790630,0.724493,0.976908,0.972401,0.983425
AAPL,0.986867,-0.866889,0.982132,1.000000,0.953876,0.978402,-0.916608,0.989809,0.990155,0.992528,...,-0.982268,0.986599,0.981173,0.965791,0.780846,0.763417,0.711675,0.980364,0.972244,0.984021
ABBV,0.966124,-0.878837,0.962255,0.953876,1.000000,0.965478,-0.872788,0.963815,0.961729,0.961352,...,-0.946553,0.953642,0.959669,0.944712,0.738942,0.835713,0.722636,0.959336,0.961472,0.965966
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
XYL,0.798226,-0.699390,0.790630,0.763417,0.835713,0.804323,-0.649222,0.789544,0.790323,0.784531,...,-0.743119,0.778951,0.827144,0.790497,0.607065,1.000000,0.685081,0.788925,0.829315,0.806878
YUM,0.703918,-0.482250,0.724493,0.711675,0.722636,0.705980,-0.517461,0.697496,0.706337,0.713643,...,-0.652017,0.730631,0.733541,0.689293,0.700624,0.685081,1.000000,0.679384,0.733734,0.685196
ZBH,0.992849,-0.913818,0.976908,0.980364,0.959336,0.989026,-0.923955,0.992692,0.989144,0.986837,...,-0.985445,0.977679,0.981140,0.976078,0.776388,0.788925,0.679384,1.000000,0.969644,0.992913
ZION,0.980650,-0.855028,0.972401,0.972244,0.961472,0.975891,-0.894861,0.980871,0.972566,0.972885,...,-0.952495,0.970087,0.971883,0.946715,0.787850,0.829315,0.733734,0.969644,1.000000,0.978813
ZTS,0.997323,-0.919405,0.983425,0.984021,0.965966,0.992014,-0.931008,0.997096,0.993811,0.988540,...,-0.986225,0.979118,0.984380,0.978122,0.774047,0.806878,0.685196,0.992913,0.978813,1.000000

In [65]:
corr_matrix.to_csv("correlation_matrix1.csv")

In [66]:
mean = portfolio_returns.mean()
std = portfolio_returns.std()

In [67]:
num_simulations = 10000
num_days = 252
simulated_returns = np.random.normal(mean, std, (num_simulations, num_days))
portfolio_paths = simulated_returns.cumsum(axis=1)

In [68]:
final_returns = portfolio_paths[:, -1]
mc_var_95 = np.percentile(final_returns, 5)
print("Monte Carlo VaR (95%):", mc_var_95)

Monte Carlo VaR (95%): -0.141593929795747

In [69]:
stress_returns = portfolio_returns - 0.10
stress_var_95 = np.percentile(stress_returns, 5)
print("Stress VaR (95%):", stress_var_95)

Stress VaR (95%): -0.1105850797983739

In [70]:
df.to_csv("alpha_pulse_final_output.csv", index=False)

In [71]:
var_data = {
    "Metric": ["VaR_95", "VaR_99", "MC_VaR_95"],
    "Value": [var_95, var_99, mc_var_95]
}
var_df = pd.DataFrame(var_data)
var_df.to_csv("var_results.csv", index=False)
print("var_results.csv created")

var_results.csv created